set -g default-terminal "xterm-256color"

# reload config file
bind r source-file ~/.tmux.conf

# use vi mode for copying
set -g mode-keys vi

# use w instead of [ for backbuffer
unbind [
bind w copy-mode

# switch panes using ctrl-jk without prefix
bind -n C-j select-pane -t:.+
bind -n C-k select-pane -t:.-

# others
set -g bell-action none
set -g display-panes-time 3000
set -g history-limit 30000
set -g renumber-windows on
set -g pane-base-index 1
set -g base-index 1

